#cargo-features = ["edition2021"]

[package]
name    = "bevy_rapier_3d_car_sim"
version = "0.1.0"
authors = [ "Alexi Chepura <a.chepura@gmail.com>" ]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
resolver = "2"

[features]
dev = []

[dependencies]
bevy = { version = "0.7.0" }
bevy_rapier3d = { git = "https://github.com/dimforge/bevy_rapier", rev = "2bec1e638ccd609e52b43266bc07a74490682b1a", features = [ "debug-render" ] }
# bevy_rapier3d = { version = "0.14.1", features = [ "debug-render" ] }
bevy_obj = "^0.7.0"
bevy-inspector-egui = "^0.11.0"
bevy-inspector-egui-rapier = { version = "0.4", features = ["rapier3d"] }
nalgebra = "^0.31.0"
rapier3d = { version = "^0.13.0", default-features = false, features = [ "dim3", "f32" ] }
smooth-bevy-cameras = { git = "https://github.com/bonsairobo/smooth-bevy-cameras" }
# smooth-bevy-cameras = "0.4.0"
rand = "0.8"

[profile.dev.package.bevy_rapier3d]
opt-level = 3

[profile.release]
codegen-units = 1

[dev-dependencies]
