#cargo-features = ["edition2021"]

[package]
name    = "bevy_rapier_3d_car_sim"
version = "0.1.0"
authors = [ "Alexi Chepura <a.chepura@gmail.com>" ]
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace]
resolver = "2"

[dependencies]
bevy = { version = "0.7.0" }
bevy_obj = "^0.7.0"
nalgebra = "^0.31.0"
rand = "0.8"
smooth-bevy-cameras = { git = "https://github.com/bonsairobo/smooth-bevy-cameras" }
bevy_polyline = "0.2"
bevy_rapier3d = { version = "0.15.0", features = [ "debug-render" ] }
# bevy_rapier3d = { git = "https://github.com/dimforge/bevy_rapier", rev = "69ea60c", features = [ "debug-render" ] }

rapier3d = { version = "^0.14.0", default-features = false, features = [ "dim3", "f32" ] }
# rapier3d = { git = "https://github.com/dimforge/rapier", rev = "06ec9a0", default-features = false, features = [ "dim3", "f32" ] }

# bevy-inspector-egui = "^0.11.0"
# bevy-inspector-egui-rapier = { version = "0.4", features = ["rapier3d"] }
# smooth-bevy-cameras = "0.4.0"

[profile.dev.package.bevy_rapier3d]
opt-level = 3

[profile.release]
codegen-units = 1

[dev-dependencies]
